release:
  github:
    owner: gleich
    name: 'fgh'
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
brews:
  - tap:
      owner: gleich
      name: homebrew-tap
    folder: Formula
    homepage: 'https://github.com/gleich/fgh'
    description: '📁 Automate the organization of your cloned GitHub repositories'
    commit_author:
      name: gleich
      email: email@mattglei.ch
    install: bin.install "fgh"
